### ISSUE TITLE
Adapt to gulp-iconfont 2.0.0

### ISSUE THREAD

**Issue by nfroidure** [cognitom/symbols-for-sketch#11]
The new version includes new features but also breaking changes.

**Comment by cognitom** [comment]
@nfroidure thanks for letting me know! I'm trying to catch up.

**Comment by cognitom** [comment]
Done :) https://github.com/cognitom/symbols-for-sketch/commit/6cf363c0926f2ea00f7249c65cea7a279e590601

I've changed `codepoint` to `glyph.unicode[0].charCodeAt(0)`.

**Comment by nfroidure** [comment]
:+1:
