### ISSUE TITLE
Transformed elements not shown properly

### ISSUE THREAD

**Issue by paesku** [cognitom/symbols-for-sketch#12]
In case anyone running into problems with transformed elements, have a look at [svgicons2svgfont](https://github.com/nfroidure/svgicons2svgfont/issues/6).

**Comment by cognitom** [comment]
@paesku thanks for your information :)
Could you add this to the [trouble shoooting](https://github.com/cognitom/symbols-for-sketch#trouble-shooting)? It seems worth to mention it there.
