### ISSUE TITLE
urgent  imac online  wait

### ISSUE THREAD

**Issue by uimake** [cognitom/symbols-for-sketch#14]
minqin-iMac:symbols-for-sketch-master eric$ npm install
npm WARN locking Error: EACCES, open '/Users/eric/.npm/_locks/lodash-33d7628955629415.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/eric/.npm/_locks/lodash-33d7628955629415.lock failed { [Error: EACCES, open '/Users/eric/.npm/_locks/lodash-33d7628955629415.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/eric/.npm/_locks/lodash-33d7628955629415.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/eric/Desktop/symbols-for-sketch-master/node_modules/lodash, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/eric/.npm/_locks/gulp-e6c74ed8c0891f04.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/eric/.npm/_locks/gulp-e6c74ed8c0891f04.lock failed { [Error: EACCES, open '/Users/eric/.npm/_locks/gulp-e6c74ed8c0891f04.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/eric/.npm/_locks/gulp-e6c74ed8c0891f04.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/eric/Desktop/symbols-for-sketch-master/node_modules/gulp, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/eric/.npm/_locks/gulp-consolidate-410a9579567f7c65.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/eric/.npm/_locks/gulp-consolidate-410a9579567f7c65.lock failed { [Error: EACCES, open '/Users/eric/.npm/_locks/gulp-consolidate-410a9579567f7c65.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/eric/.npm/_locks/gulp-consolidate-410a9579567f7c65.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/eric/Desktop/symbols-for-sketch-master/node_modules/gulp-consolidate, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/eric/.npm/_locks/gulp-iconfont-5615a23f45f66c9a.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/eric/.npm/_locks/gulp-iconfont-5615a23f45f66c9a.lock failed { [Error: EACCES, open '/Users/eric/.npm/_locks/gulp-iconfont-5615a23f45f66c9a.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/eric/.npm/_locks/gulp-iconfont-5615a23f45f66c9a.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/eric/Desktop/symbols-for-sketch-master/node_modules/gulp-iconfont, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/eric/.npm/_locks/gulp-sketch-55bf99522704021c.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/eric/.npm/_locks/gulp-sketch-55bf99522704021c.lock failed { [Error: EACCES, open '/Users/eric/.npm/_locks/gulp-sketch-55bf99522704021c.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/eric/.npm/_locks/gulp-sketch-55bf99522704021c.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/eric/Desktop/symbols-for-sketch-master/node_modules/gulp-sketch, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/eric/.npm/_locks/coffee-script-71bf1ad99445843a.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/eric/.npm/_locks/coffee-script-71bf1ad99445843a.lock failed { [Error: EACCES, open '/Users/eric/.npm/_locks/coffee-script-71bf1ad99445843a.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/eric/.npm/_locks/coffee-script-71bf1ad99445843a.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/eric/Desktop/symbols-for-sketch-master/node_modules/coffee-script, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/eric/.npm/_locks/gulp-rename-6bbaad98c612ab56.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/eric/.npm/_locks/gulp-rename-6bbaad98c612ab56.lock failed { [Error: EACCES, open '/Users/eric/.npm/_locks/gulp-rename-6bbaad98c612ab56.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/eric/.npm/_locks/gulp-rename-6bbaad98c612ab56.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/eric/Desktop/symbols-for-sketch-master/node_modules/gulp-rename, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eric/Desktop/symbols-for-sketch-master/npm-debug.log
minqin-iMac:symbols-for-sketch-master eric$ 

my english is disaster. so i hope you  reply ：step 1,step 2,step 3...    thank you

**Comment by cognitom** [comment]
That seems not the matter of Symbols for Sketch. I recommend you to reinstall node.js again.
