### ISSUE TITLE
IE9 doesn't show the icons

### ISSUE THREAD

**Issue by smaxii** [cognitom/symbols-for-sketch#15]
Hi ,
    I used symbols-for-sketch to generate the font icon.The sample.html works fine under chrome and firefox,but when we test it under IE, IE11 works fine too,but the icons can't be shown under IE9.Could you take a look at this?Thanks.

**Comment by cognitom** [comment]
Have you check this case?
https://github.com/cognitom/symbols-for-sketch#case-1-icons-with-circle-filled-with-black

**Comment by Neema** [comment]
What is your font named? Can you post your final font somewhere so I can take a look @smaxii
