### ISSUE TITLE
Error: spawn sketchtool ENOENT

### ISSUE THREAD

**Issue by itamark** [cognitom/symbols-for-sketch#16]
Hey - I downloaded and ran npm and gulp and am receiving the following error:
```
Error: spawn sketchtool ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```
Can't find a previous error on this so wondering if you know what you think it might be.

**Comment by cognitom** [comment]
Have you already installed `sketchtools`? This tool completely depends on that.

**Comment by itamark** [comment]
@cognitom amazing response time - thanks. You're right!
