### ISSUE TITLE
Please remove the "sudo" from your Readme instructions

### ISSUE THREAD

**Issue by hulkish** [cognitom/symbols-for-sketch#18]
Please remove the "sudo" as part of your instructions for installing gulp. Installing global modules globally via sudo is generally very ill-advised

**Comment by cognitom** [comment]
Yeah, I know. When I wrote it, `sudo` was needed because of the official GUI installer for Mac. But, basically I'm using modebrew, so I don't know `sudo` is still needed or not.
Is it solved In current version?

**Comment by hulkish** [comment]
sudo has been a non issue for me at least for a while now,  by way of restoring global moduoes in my home directory by using: 

```npm config set prefix ~/.npm```

Then making sure that it's bin folder is added to my PATH environment variable,  in my `.bash_profile`:

```export $PATH=$HOME/.npm/bin:$PATH```

**Comment by cognitom** [comment]
@hulkish thanks. Still not clear for me that users can install globally without extra steps. I think this is not a tutorial for installing Node, and many readers are DESIGNERS who don't like black screens.

Then, how about this way?

-----
Type the command below to install gulp.

```bash
$ npm install -g gulp
```

If you encounter some trouble during install, try with `sudo`:

```bash
$ sudo npm install -g gulp
```
