### ISSUE TITLE
14px file stops working for no reason

### ISSUE THREAD

**Issue by itamark** [cognitom/symbols-for-sketch#19]
I have been using symbols-for-sketch, and now 14px doesn't work. Nothing has changed, and I tested it on a newly pulled 14px sketch file, still doesn't work.

**Comment by cognitom** [comment]
Hi @itamark what version of Sketch are you using?

**Comment by itamark** [comment]
I'm on 3.4 - is that the issue? It seems that right off your repo- the build works. But once the file is edited at all, it doesn't.
Thanks for the response!

**Comment by cognitom** [comment]
Have you update `sketchtool`, too?

**Comment by kendrick** [comment]
Was running into the exact same issue as @itamark on Sketch 3.4. Updating Sketchtool to the latest version fixed it for me.

**Comment by itamark** [comment]
Oddly enough - I updated sketchool and it's still not working. Sketch is at 3.4.1 but sketchtool is up to date and not working properly still. Do you think degrading to 3.4 will fix it?

**Comment by kendrick** [comment]
I can't say for sure but it may be worth a shot. FWIW I've only got Sketch
3.4 installed (not 3.4.1) and `sketchtool -v` reports Version 3.4 (375).

**Comment by itamark** [comment]
Okay my sketchtool is way out of date. How do I update it?

**Comment by cognitom** [comment]
@itamark try this:

```bash
$ curl -L https://raw.githubusercontent.com/cognitom/dotfiles/master/lib/sketchtool.sh | sudo sh
```

**Comment by itamark** [comment]
worked!

**Comment by cognitom** [comment]
:smile_cat:
