### ISSUE TITLE
Generated fonts not working on windows/linux

### ISSUE THREAD

**Issue by TimNuman** [cognitom/symbols-for-sketch#2]
Hi, 

Great project!
I tried making my own icon font, and it all worked fine on my mac.
However, when I try to view the generated icons on windows or linux, a lot of icons are 'filled'. So a circle with a one it it looks fine on osx, but is a completely black circle on win/linux.

Is there a special way to draw the icons or is this an export issue?

Thanks!

**Comment by bjmin** [comment]
OMG!
