### ISSUE TITLE
Icons generated small 

### ISSUE THREAD

**Issue by itamark** [cognitom/symbols-for-sketch#23]
I'm getting my icons small and below the line-height for some reason. Anyone else experience this?

<img width="382" alt="screen shot 2015-12-12 at 4 22 14 pm" src="https://cloud.githubusercontent.com/assets/1757393/11762366/a5dc5d6a-a0ec-11e5-99e9-76a4e36e65c0.png">

**Comment by cognitom** [comment]
Hi @itamark, I've never seen this issue. Have you already tried [the original file](https://github.com/cognitom/symbols-for-sketch/blob/master/symbol-font-14px.sketch) with your current settings?

**Comment by itamark** [comment]
Works fine with the original file.
The only difference I can think of is that mine has multiple pages. Could that affect it?

**Comment by cognitom** [comment]
If you have smaller icons on another page, it could be.

**Comment by itamark** [comment]
Perfect - that was it. Removed the other pages and it worked. Thanks!
