### ISSUE TITLE
No longer generating a font

### ISSUE THREAD

**Issue by melissaboucher** [cognitom/symbols-for-sketch#27]
I'm currently experiencing issues with generating webfont files from my updated Sketch files. The last time I used this script was November 2015. Is anyone seeing the same thing? Any chance it has to do with the Sketch 3.7 update?

**Comment by peacepostman** [comment]
Hello,

I think you may have the same problem we've had a couple month ago, just reinstall sketchTool from sketch folder

https://github.com/cognitom/symbols-for-sketch/issues/26

Have a nice day

**Comment by melissaboucher** [comment]
Yes, that worked! Thanks so much for your help!
